=== DmitryAkulich33/epam_tasks/task13/src/main/resources/xml/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.training.by/orders"
        xmlns:tns="http://www.epam.training.by/orders" elementFormDefault="qualified">
    <element name="orders">
        <complexType>
            <sequence>
                <element name="order" type="tns:Order" maxOccurs="unbounded"
                         minOccurs="1"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Order">
        <sequence>
            <element name="client" type="tns:Client"/>
            <element name="pie" type="tns:Pie"/>
            <element name="productionDate" type="dateTime"/>
            <element name="deliveryDate" type="dateTime"/>
        </sequence>
        <attribute type="tns:Unique" name="id" use="required" />
        <attribute name="status" use="optional" default="not ready">
            <simpleType>
                <restriction base="string">
                    <enumeration value="not ready"/>
                    <enumeration value="ready"/>
                    <enumeration value="delivered"/>
                    <enumeration value="undelivered"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <simpleType name="Unique">
        <restriction base="integer">
            <pattern value="[0-9]+"/>
        </restriction>
    </simpleType>
    <complexType name="Client">
        <sequence>
            <element name="surname" type="string"/>
            <element name="name" type="string"/>
            <element name="patronymic" type="string"/>
            <element name="address" type="string"/>
            <element name="phone" type="string"/>
            <element name="note" type="string"/>
        </sequence>
        <attribute type="tns:Unique" name="id" use="required" />
    </complexType>
    <complexType name="Pie">
        <sequence>
            <element name="title" type="string"/>
            <element name="weight" type="int"/>
            <element name="price" type="double"/>
            <element name="description" type="string"/>
        </sequence>
        <attribute type="tns:Unique" name="id" use="required" />
    </complexType>
</schema>

=== DmitryAkulich33/epam_tasks/task13/src/test/resources/ordersTest2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.epam.training.by/orders" xsi:schemaLocation="http://www.epam.training.by/classes orders.xsd">
    <order id="1" status="delivered">
        <client id="1">
            <surname>Ivanov</surname>
            <name>Ivan</name>
            <patronymic>Ivanovich</patronymic>
            <address>Apt 18, 44 Rafieva St, Minsk</address>
            <phone>+375 29 7434546</phone>
            <note>In the yard problems with parking spaces</note>
        </client>
        <pie id="1">
            <title>Belorussian</title>
            <weight>1000</weight>
            <price>24.00</price>
            <description>Signature dough, rustic potatoes, with cracklings, fried mushrooms, caraway seeds and coriander</description>
        </pie>
        <productionDate>2020-01-30T09:00:00</productionDate>
        <deliveryDate>2020-01-30T12:30:00</deliveryDate>
    </order>
    <order id="2" status="delivered">
        <client id="3">
            <surname>Sidorov</surname>
            <name>Sidr</name>
            <patronymic>Sidorovich</patronymic>
            <address>Apt 95, 27 Lubimova St, Minsk</address>
            <phone>+375 44 5982331</phone>
            <note>Near the house there are construction work</note>
        </client>
        <pie id="2">
            <title>Italian</title>
            <weight>950</weight>
            <price>22.00</price>
            <description>Signature dough, sunny lemon with vitamin zest and peppermint</description>
        </pie>
        <productionDate>2020-01-31T10:00:00</productionDate>
        <deliveryDate>2020-01-31T12:30:00</deliveryDate>
    </order>
</orders>
